version: '3.1'

services:
  pedrojs:
    container_name: devenv_ether_minter
    image: ether-minter:latest
    restart: always
    volumes:
      - ../conf:/opt/app/conf
    ports:
      - "27550:27550"
