cluster:
  name: cluster-name
  id: a8e3835e-ff2b-47ee-bdae-452676d8a73e
  description: 'cluster description'

network:
  ip: 0.0.0.0
  httpServer:
    enable: true
    port: 27550
  httpsServer:
    enable: false
    port: 27550
    mutualTLS: false

serviceInfo:
  version: v1
  hostName: HostName
  serviceName: ether-minter
  processName: ether-minter
  ip: 127.0.0.1
  port: 27550
  tags:
    - microservice
    - typescript
    - docker
  id: 7c9e8254-515d-4115-a177-22628525e1d7

log:
  level: DEBUG

custom:
  mint:
    # NFT contract owner
    contractOwner:
      address: 'CONTRACT_OWNER_ADDRESS'
      keyStoreSK: ''

    # Gas price threshold
    gasPrice:
      # Gas upper threshold (unit: Gwei)
      # If the gas price is higher than this threshold, mint request will be dropped.
      # Leave empty to disable.
      upper:
        threshold: '100'
        # Sends a notification when gas price goes above a threshold.
        callback: ''

      # Gas lower threshold (unit: Gwei)
      # Leave empty to disable.
      lower:
        threshold: '50'
        # Sends a notification when gas price goes below a threshold.
        callback: ''

    # RESTFul API response code
    apiResponseCode:
      OK: 'YOUR_RESPONSE_CODE'
      ERROR: 'YOUR_RESPONSE_CODE'
      THRESHOLD: 'YOUR_RESPONSE_CODE'
      DUPLICATE: 'YOUR_RESPONSE_CODE'
      NOTFOUND: 'YOUR_RESPONSE_CODE'
      MAXSUPPLY: 'YOUR_RESPONSE_CODE'

    # Mints NFT by random minter, set 'true' to enable (Optional)
    randomMinter: true

    # Minter list
    minterList:
      - address: 'MINTER_1_ADDRESS'
        keyStoreSK: ''
      - address: 'MINTER_2_ADDRESS'
        keyStoreSK: ''

  # Default network
  defaultNetwork:
    # Chain name
    chain: polygon
    # Network name
    network: mainnet
    # Use provider pool
    providerPool: true

  tx:
    # GasLimit coefficient (%)
    # Example: 110 means gasLimit * 110%
    gasLimitC: 110
    # Transfer confirmations
    confirmations: 3

  networks:
    # Ethereum
    ethereum:
      mainnet:
        # Chain ID
        chainId: 1
        # Provider URL
        provider:
          - 'YOUR PROVIDER'
        # Blockchain explorer URL
        browser: https://etherscan.io

      ropsten:
        chainId: 3
        provider:
          - 'YOUR PROVIDER'
        browser: https://ropsten.etherscan.io

      rinkeby:
        chainId: 4
        provider:
          - 'YOUR PROVIDER'
        browser: https://rinkeby.etherscan.io

      goerli:
        chainId: 5
        provider:
          - 'YOUR PROVIDER'
        browser: https://goerli.etherscan.io

    # Polygon
    # Ref: https://docs.polygon.technology/docs/develop/network-details/network
    polygon:
      mainnet:
        chainId: 137
        provider:
          - https://polygon-rpc.com
          - https://matic-mainnet.chainstacklabs.com
          - https://rpc-mainnet.maticvigil.com
          - https://rpc-mainnet.matic.quiknode.pro
        browser: https://polygonscan.com

      mumbai:
        chainId: 80001
        provider:
          - https://rpc-mumbai.matic.today
          - https://matic-mumbai.chainstacklabs.com
        browser: https://mumbai.polygonscan.com

    # Local Development
    dev:
      local:
        chainId: 666
        provider:
          - http://localhost:8545
        browser: http://localhost:4000
